apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reeldev-ghcr
  namespace: reeldev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    type: kubernetes.io/dockerconfigjson
    template:
      data:
        .dockerconfigjson: '{"auths":{"{{ .docker_server }}":{"username":"{{ .docker_username }}","password":"{{ .docker_password }}","auth":"{{ printf "%s:%s" .docker_username .docker_password | b64enc }}"}}}'
  data:
  - secretKey: docker_server
    remoteRef:
      key: reeldev-ghcr
      property: docker_server
  - secretKey: docker_username
    remoteRef:
      key: reeldev-ghcr
      property: docker_username
  - secretKey: docker_password
    remoteRef:
      key: reeldev-ghcr
      property: docker_password
