apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reeldev-secret
  namespace: reeldev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: reeldev-secret
  data:
  - secretKey: ADMIN_API_KEY
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: ADMIN_API_KEY
  - secretKey: SESSION_SECRET
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: SESSION_SECRET
  - secretKey: DISCORD_CLIENT_ID
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: DISCORD_CLIENT_ID
  - secretKey: DISCORD_CLIENT_SECRET
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: DISCORD_CLIENT_SECRET
  - secretKey: DISCORD_REDIRECT_URI
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: DISCORD_REDIRECT_URI
  - secretKey: ALLOWED_DISCORD_IDS
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: ALLOWED_DISCORD_IDS
  - secretKey: QIITA_USER
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: QIITA_USER
  - secretKey: QIITA_TOKEN
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: QIITA_TOKEN
  - secretKey: API_BASE
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: API_BASE
  - secretKey: CORS_ORIGIN
    remoteRef:
      key: common/secret/data/reeldev-secret
      property: CORS_ORIGIN
