apiVersion: v1
kind: PersistentVolume
metadata:
  name: reeldev-data-pv-dev
  labels:
    capsule.clastix.io/tenant: dev
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 172.16.245.255
    path: /export/k8s/pvc/reeldev/reeldev-data-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reeldev-data-dev
  namespace: reeldev-dev
  labels:
    capsule.clastix.io/tenant: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: reeldev-data-pv-dev
